import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  DECANS_LOOKUP_FIXTURES,
  getDecansFixture,
  getDecansFixtureCategories,
  getDecansFixtureIds,
} from './fixtures/decansFixtures.js';

const REQUIRED_CATEGORIES = Object.freeze([
  'signStarts',
  'exactBoundaries',
  'finalBoundary',
  'invalidInputs',
  'planetInput',
  'summary',
  'sourceSystemSeparation',
  'strictExclusions',
]);

const FORBIDDEN_FIXTURE_STRINGS = Object.freeze([
  'Егор',
  'Анна',
  'birthDate',
  'birthTime',
  'coordinates',
  'profileJson',
  'fullProfile',
  'trigonDecans',
  'degreeRulers',
  'interpretation',
  'ритуал',
  'uranus',
  'neptune',
  'pluto',
  'Уран',
  'Нептун',
  'Плутон',
]);

test('DECANS_LOOKUP_FIXTURES is an array of fixture objects', () => {
  assert.equal(Array.isArray(DECANS_LOOKUP_FIXTURES), true);
  assert.ok(DECANS_LOOKUP_FIXTURES.length >= REQUIRED_CATEGORIES.length);

  for (const fixture of DECANS_LOOKUP_FIXTURES) {
    assert.equal(typeof fixture.id, 'string');
    assert.equal(typeof fixture.category, 'string');
    assert.equal(typeof fixture.label, 'string');
    assert.equal(typeof fixture.input, 'object');
    assert.equal(typeof fixture.expected, 'object');
    assert.equal(Array.isArray(fixture.notes), true);
  }
});

test('fixture ids are unique and getter helpers work', () => {
  const ids = getDecansFixtureIds();

  assert.deepEqual(ids, DECANS_LOOKUP_FIXTURES.map((fixture) => fixture.id));
  assert.equal(new Set(ids).size, ids.length);
  assert.equal(getDecansFixture(ids[0])?.id, ids[0]);
  assert.equal(getDecansFixture('unknown-decans-fixture'), null);
});

test('required decans fixture categories exist', () => {
  const categories = getDecansFixtureCategories();

  for (const category of REQUIRED_CATEGORIES) {
    assert.equal(categories.includes(category), true, `${category} category should exist`);
  }
});

test('expected values are manually present in fixture data', () => {
  for (const fixture of DECANS_LOOKUP_FIXTURES) {
    assert.equal(typeof fixture.expected.status, 'string');

    if (fixture.expected.status === 'ready') {
      assert.equal(Number.isFinite(fixture.expected.decanIndex), true);
      assert.equal(typeof fixture.expected.ruler, 'string');
      assert.equal(Number.isFinite(fixture.expected.startDegree), true);
      assert.equal(Number.isFinite(fixture.expected.endDegreeExclusive), true);
      assert.equal(fixture.expected.sourceSystem, 'star-of-magi-egyptian-tradition');
    }

    if (fixture.expected.status === 'invalid') {
      assert.equal(typeof fixture.expected.reason, 'string');
    }

    if (fixture.expected.status === 'summary') {
      assert.equal(Number.isFinite(fixture.expected.total), true);
      assert.equal(Number.isFinite(fixture.expected.ready), true);
      assert.equal(typeof fixture.expected.byRuler, 'object');
      assert.equal(typeof fixture.expected.byDecanIndex, 'object');
    }
  }
});

test('decans fixtures contain no private data unsupported source rows or interpretation text', () => {
  const fixtureText = JSON.stringify(DECANS_LOOKUP_FIXTURES);

  for (const forbidden of FORBIDDEN_FIXTURE_STRINGS) {
    assert.equal(fixtureText.includes(forbidden), false, `${forbidden} should not be present`);
  }
});

test('planet fixture records use synthetic source metadata', () => {
  for (const fixture of DECANS_LOOKUP_FIXTURES.filter((item) => item.category === 'planetInput')) {
    assert.equal(fixture.input.planet.source, 'synthetic-fixture');
  }
});

test('expected values are not generated by the decans lookup engine at fixture creation time', () => {
  const source = readFileSync(new URL('./fixtures/decansFixtures.js', import.meta.url), 'utf8');

  assert.equal(source.includes('../src/decans.js'), false);
  assert.equal(source.includes('lookupDecan'), false);
  assert.equal(source.includes('lookupDecanForPlanet'), false);
  assert.equal(source.includes('evaluateDecansForPlanets'), false);
});
