import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  DEGREE_RULERS_STAR_OF_MAGI_LOOKUP_FIXTURES,
  getDegreeRulersStarOfMagiFixture,
  getDegreeRulersStarOfMagiFixtureCategories,
  getDegreeRulersStarOfMagiFixtureIds,
} from './fixtures/degreeRulersStarOfMagiFixtures.js';

const REQUIRED_CATEGORIES = Object.freeze([
  'signStarts',
  'fractionalBoundaries',
  'integerBoundaries',
  'invalidInputs',
  'planetInput',
  'summary',
  'sourceSystemSeparation',
  'strictExclusions',
]);

const FORBIDDEN_FIXTURE_STRINGS = Object.freeze([
  'Егор',
  'Анна',
  'birthDate',
  'birthTime',
  'coordinates',
  'profileJson',
  'fullProfile',
  'Table 7',
  'Vronsky degree rulers',
  'vronsky-degree-rulers',
  'retrograde',
  'multipleRulers',
  'trigon',
  'decans',
  'terms',
  'interpretation',
  'ритуал',
  'uranus',
  'neptune',
  'pluto',
  'Уран',
  'Нептун',
  'Плутон',
]);

const SEPTENER_RULERS = Object.freeze([
  'sun',
  'moon',
  'mercury',
  'venus',
  'mars',
  'jupiter',
  'saturn',
]);

test('DEGREE_RULERS_STAR_OF_MAGI_LOOKUP_FIXTURES is an array of fixture objects', () => {
  assert.equal(Array.isArray(DEGREE_RULERS_STAR_OF_MAGI_LOOKUP_FIXTURES), true);
  assert.ok(DEGREE_RULERS_STAR_OF_MAGI_LOOKUP_FIXTURES.length >= REQUIRED_CATEGORIES.length);

  for (const fixture of DEGREE_RULERS_STAR_OF_MAGI_LOOKUP_FIXTURES) {
    assert.equal(typeof fixture.id, 'string');
    assert.equal(typeof fixture.category, 'string');
    assert.equal(typeof fixture.label, 'string');
    assert.equal(typeof fixture.input, 'object');
    assert.equal(typeof fixture.expected, 'object');
    assert.equal(Array.isArray(fixture.notes), true);
  }
});

test('fixture ids are unique and getter helpers work', () => {
  const ids = getDegreeRulersStarOfMagiFixtureIds();

  assert.deepEqual(ids, DEGREE_RULERS_STAR_OF_MAGI_LOOKUP_FIXTURES.map((fixture) => fixture.id));
  assert.equal(new Set(ids).size, ids.length);
  assert.equal(getDegreeRulersStarOfMagiFixture(ids[0])?.id, ids[0]);
  assert.equal(getDegreeRulersStarOfMagiFixture('unknown-degree-ruler-fixture'), null);
});

test('required degree ruler fixture categories exist', () => {
  const categories = getDegreeRulersStarOfMagiFixtureCategories();

  for (const category of REQUIRED_CATEGORIES) {
    assert.equal(categories.includes(category), true, `${category} category should exist`);
  }
});

test('expected values are manually present in fixture data', () => {
  for (const fixture of DEGREE_RULERS_STAR_OF_MAGI_LOOKUP_FIXTURES) {
    assert.equal(typeof fixture.expected.status, 'string');

    if (fixture.expected.status === 'ready') {
      assert.equal(Number.isInteger(fixture.expected.degreeIndex), true);
      assert.equal(typeof fixture.expected.ruler, 'string');
      assert.equal(SEPTENER_RULERS.includes(fixture.expected.ruler), true);
      assert.equal(fixture.expected.sourceSystem, 'star-of-magi-degree-rulers');
    }

    if (fixture.expected.status === 'invalid') {
      assert.equal(typeof fixture.expected.reason, 'string');
    }

    if (fixture.expected.status === 'summary') {
      assert.equal(Number.isFinite(fixture.expected.total), true);
      assert.equal(Number.isFinite(fixture.expected.ready), true);
      assert.equal(typeof fixture.expected.byRuler, 'object');
    }
  }
});

test('degree ruler fixtures contain no private data deferred rows or interpretation text', () => {
  const fixtureText = JSON.stringify(DEGREE_RULERS_STAR_OF_MAGI_LOOKUP_FIXTURES);

  for (const forbidden of FORBIDDEN_FIXTURE_STRINGS) {
    assert.equal(fixtureText.includes(forbidden), false, `${forbidden} should not be present`);
  }
});

test('planet fixture records use synthetic source metadata', () => {
  for (const fixture of DEGREE_RULERS_STAR_OF_MAGI_LOOKUP_FIXTURES.filter((item) => item.category === 'planetInput')) {
    assert.equal(fixture.input.planet.source, 'synthetic-fixture');
  }
});

test('expected values are not generated by the degree ruler lookup engine at fixture creation time', () => {
  const source = readFileSync(new URL('./fixtures/degreeRulersStarOfMagiFixtures.js', import.meta.url), 'utf8');

  assert.equal(source.includes('../src/degreeRulersStarOfMagi.js'), false);
  assert.equal(source.includes('lookupDegreeRuler'), false);
  assert.equal(source.includes('lookupDegreeRulerForPlanet'), false);
  assert.equal(source.includes('evaluateDegreeRulersForPlanets'), false);
});
