import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  ESSENTIAL_DIGNITY_FIXTURES,
  getEssentialDignityFixture,
  getEssentialDignityFixtureCategories,
  getEssentialDignityFixtureIds,
} from './fixtures/essentialDignityFixtures.js';

const REQUIRED_CATEGORIES = Object.freeze([
  'domicile',
  'detriment',
  'exaltation',
  'fall',
  'multipleFlags',
  'modernRulership',
  'neutral',
  'invalidPlanets',
  'summary',
  'strictExclusions',
]);

const PRIVATE_OR_UNSUPPORTED_FIXTURE_STRINGS = Object.freeze([
  'Егор',
  'Анна',
  'birthDate',
  'birthTime',
  'coordinates',
  'profileJson',
  'fullProfile',
  'terms',
  'decans',
  'degreeRulers',
  'exactExaltationDegrees',
  'exaltationDegreeValues',
  'Vronsky',
  'interpretationText',
]);

test('ESSENTIAL_DIGNITY_FIXTURES is an array of fixture objects', () => {
  assert.equal(Array.isArray(ESSENTIAL_DIGNITY_FIXTURES), true);
  assert.ok(ESSENTIAL_DIGNITY_FIXTURES.length >= REQUIRED_CATEGORIES.length);

  for (const fixture of ESSENTIAL_DIGNITY_FIXTURES) {
    assert.equal(typeof fixture.id, 'string');
    assert.equal(typeof fixture.label, 'string');
    assert.equal(typeof fixture.category, 'string');
    assert.equal(typeof fixture.description, 'string');
    assert.equal(Array.isArray(fixture.planets), true);
    assert.equal(typeof fixture.expected, 'object');
    assert.equal(typeof fixture.expected.resultCount, 'number');
    assert.equal(Array.isArray(fixture.expected.results), true);
    assert.equal(Array.isArray(fixture.notes), true);
  }
});

test('fixture ids are unique and getter helpers work', () => {
  const ids = getEssentialDignityFixtureIds();

  assert.deepEqual(ids, ESSENTIAL_DIGNITY_FIXTURES.map((fixture) => fixture.id));
  assert.equal(new Set(ids).size, ids.length);
  assert.equal(getEssentialDignityFixture(ids[0])?.id, ids[0]);
  assert.equal(getEssentialDignityFixture('unknown-essential-dignity-fixture'), null);
});

test('required fixture categories exist', () => {
  const categories = getEssentialDignityFixtureCategories();

  for (const category of REQUIRED_CATEGORIES) {
    assert.equal(categories.includes(category), true);
  }
});

test('fixtures do not contain private profile names or unsupported data rows', () => {
  const fixtureText = JSON.stringify(ESSENTIAL_DIGNITY_FIXTURES);

  for (const forbidden of PRIVATE_OR_UNSUPPORTED_FIXTURE_STRINGS) {
    assert.equal(fixtureText.includes(forbidden), false);
  }
});

test('all fixture planet rows use synthetic fixture source metadata', () => {
  for (const fixture of ESSENTIAL_DIGNITY_FIXTURES) {
    for (const planet of fixture.planets) {
      assert.equal(planet.source, 'synthetic-fixture');
    }
  }
});

test('expected results are declared in fixture data, not generated by the engine module', () => {
  const source = readFileSync(new URL('./fixtures/essentialDignityFixtures.js', import.meta.url), 'utf8');

  assert.equal(source.includes('../src/essentialDignities.js'), false);
  assert.equal(source.includes('evaluateEssentialDignity'), false);
  assert.equal(source.includes('evaluateEssentialDignities'), false);
});

test('fixtures contain manually declared expected results for all non-invalid categories', () => {
  for (const fixture of ESSENTIAL_DIGNITY_FIXTURES) {
    if (fixture.category === 'invalidPlanets') {
      assert.equal(fixture.expected.results.length, 0);
      continue;
    }

    assert.ok(fixture.expected.results.length > 0);

    for (const expected of fixture.expected.results) {
      assert.equal(typeof expected.planetKey, 'string');
      assert.equal(typeof expected.signKey, 'string');
      assert.equal(typeof expected.dignities, 'object');
      assert.equal(Number.isFinite(expected.score), true);
      assert.equal(Array.isArray(expected.labels), true);
      assert.equal(Array.isArray(expected.modernLabels), true);
    }
  }
});

test('fixtures contain no interpretation copy or future dignity source-pack keys', () => {
  const fixtureText = JSON.stringify(ESSENTIAL_DIGNITY_FIXTURES);

  assert.equal(fixtureText.includes('плох'), false);
  assert.equal(fixtureText.includes('опас'), false);
  assert.equal(fixtureText.includes('судь'), false);
  assert.equal(fixtureText.includes('ритуал'), false);
  assert.equal(fixtureText.includes('fixedStars'), false);
  assert.equal(fixtureText.includes('houses'), false);
  assert.equal(fixtureText.includes('ASC'), false);
  assert.equal(fixtureText.includes('transits'), false);
});
