import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  NATAL_ASPECT_FIXTURES,
  REQUIRED_NATAL_ASPECT_FIXTURE_CATEGORIES,
  getNatalAspectFixture,
  getNatalAspectFixtureCategories,
  getNatalAspectFixtureIds,
} from './fixtures/natalAspectFixtures.js';

test('NATAL_ASPECT_FIXTURES is array', () => {
  assert.equal(Array.isArray(NATAL_ASPECT_FIXTURES), true);
  assert.equal(NATAL_ASPECT_FIXTURES.length > 0, true);
});

test('every natal aspect fixture has required shape', () => {
  NATAL_ASPECT_FIXTURES.forEach((fixture) => {
    assert.equal(typeof fixture.id, 'string');
    assert.equal(fixture.id.length > 0, true);
    assert.equal(typeof fixture.label, 'string');
    assert.equal(fixture.label.length > 0, true);
    assert.equal(typeof fixture.category, 'string');
    assert.equal(fixture.category.length > 0, true);
    assert.equal(typeof fixture.description, 'string');
    assert.equal(Array.isArray(fixture.planets), true);
    assert.equal(typeof fixture.expected, 'object');
    assert.equal(Number.isInteger(fixture.expected.aspectCount), true);
    assert.equal(Array.isArray(fixture.expected.aspects), true);
  });
});

test('fixture ids are unique', () => {
  const ids = getNatalAspectFixtureIds();

  assert.equal(new Set(ids).size, ids.length);
});

test('getNatalAspectFixture returns fixture or null', () => {
  const [firstId] = getNatalAspectFixtureIds();

  assert.equal(getNatalAspectFixture(firstId)?.id, firstId);
  assert.equal(getNatalAspectFixture('unknown-natal-aspect-fixture'), null);
});

test('natal aspect fixtures contain no private user names or profile JSON', () => {
  const text = JSON.stringify(NATAL_ASPECT_FIXTURES);
  const forbidden = [
    'Егор',
    'Анна',
    'birthDate',
    'birthTime',
    'birthPlace',
    'currentPlace',
    'coordinates',
    'schemaVersion',
    'profiles',
    'profile JSON',
  ];

  forbidden.forEach((value) => {
    assert.equal(text.includes(value), false, `${value} should not be present`);
  });
});

test('all fixture planet records use synthetic source', () => {
  NATAL_ASPECT_FIXTURES.forEach((fixture) => {
    fixture.planets.forEach((planet) => {
      assert.equal(planet.source, 'synthetic-fixture');
    });
  });
});

test('expected aspects are manually declared and not generated by engine at fixture creation time', () => {
  const source = readFileSync(new URL('./fixtures/natalAspectFixtures.js', import.meta.url), 'utf8');

  assert.equal(source.includes('calculateNatalAspects'), false);
  assert.equal(source.includes('calculateNatalAspectBetween'), false);
  assert.equal(source.includes('natalAspectEngine'), false);
});

test('required natal aspect fixture categories exist', () => {
  const categories = getNatalAspectFixtureCategories();

  REQUIRED_NATAL_ASPECT_FIXTURE_CATEGORIES.forEach((category) => {
    assert.equal(categories.includes(category), true, `${category} category should exist`);
  });
});
