import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  TERMS_LOOKUP_FIXTURES,
  getTermsFixture,
  getTermsFixtureCategories,
  getTermsFixtureIds,
} from './fixtures/termsFixtures.js';

const REQUIRED_CATEGORIES = Object.freeze([
  'signStarts',
  'exactBoundaries',
  'finalPrinted29Normalization',
  'finalPrinted30',
  'invalidInputs',
  'planetInput',
  'summary',
  'strictExclusions',
]);

const FORBIDDEN_FIXTURE_STRINGS = Object.freeze([
  'Егор',
  'Анна',
  'birthDate',
  'birthTime',
  'coordinates',
  'profileJson',
  'fullProfile',
  'degreeRulers',
  'decans',
  'interpretation',
  'ритуал',
]);

test('TERMS_LOOKUP_FIXTURES is an array of fixture objects', () => {
  assert.equal(Array.isArray(TERMS_LOOKUP_FIXTURES), true);
  assert.ok(TERMS_LOOKUP_FIXTURES.length >= REQUIRED_CATEGORIES.length);

  for (const fixture of TERMS_LOOKUP_FIXTURES) {
    assert.equal(typeof fixture.id, 'string');
    assert.equal(typeof fixture.category, 'string');
    assert.equal(typeof fixture.label, 'string');
    assert.equal(typeof fixture.input, 'object');
    assert.equal(typeof fixture.expected, 'object');
    assert.equal(Array.isArray(fixture.notes), true);
  }
});

test('fixture ids are unique and getter helpers work', () => {
  const ids = getTermsFixtureIds();

  assert.deepEqual(ids, TERMS_LOOKUP_FIXTURES.map((fixture) => fixture.id));
  assert.equal(new Set(ids).size, ids.length);
  assert.equal(getTermsFixture(ids[0])?.id, ids[0]);
  assert.equal(getTermsFixture('unknown-terms-fixture'), null);
});

test('required terms fixture categories exist', () => {
  const categories = getTermsFixtureCategories();

  for (const category of REQUIRED_CATEGORIES) {
    assert.equal(categories.includes(category), true, `${category} category should exist`);
  }
});

test('expected values are manually present in fixture data', () => {
  for (const fixture of TERMS_LOOKUP_FIXTURES) {
    assert.equal(typeof fixture.expected.status, 'string');

    if (fixture.expected.status === 'ready') {
      assert.equal(typeof fixture.expected.ruler, 'string');
      assert.equal(Number.isFinite(fixture.expected.value), true);
      assert.equal(Number.isFinite(fixture.expected.startDegree), true);
      assert.equal(Number.isFinite(fixture.expected.printedEndDegree), true);
      assert.equal(Number.isFinite(fixture.expected.normalizedEndExclusive), true);
    }

    if (fixture.expected.status === 'invalid') {
      assert.equal(typeof fixture.expected.reason, 'string');
    }

    if (fixture.expected.status === 'summary') {
      assert.equal(Number.isFinite(fixture.expected.total), true);
      assert.equal(Number.isFinite(fixture.expected.ready), true);
      assert.equal(Number.isFinite(fixture.expected.scoreTotal), true);
      assert.equal(typeof fixture.expected.byRuler, 'object');
    }
  }
});

test('terms fixtures contain no private data unsupported source rows or interpretation text', () => {
  const fixtureText = JSON.stringify(TERMS_LOOKUP_FIXTURES);

  for (const forbidden of FORBIDDEN_FIXTURE_STRINGS) {
    assert.equal(fixtureText.includes(forbidden), false, `${forbidden} should not be present`);
  }
});

test('planet fixture records use synthetic source metadata', () => {
  for (const fixture of TERMS_LOOKUP_FIXTURES.filter((item) => item.category === 'planetInput')) {
    assert.equal(fixture.input.planet.source, 'synthetic-fixture');
  }
});

test('expected values are not generated by the terms lookup engine at fixture creation time', () => {
  const source = readFileSync(new URL('./fixtures/termsFixtures.js', import.meta.url), 'utf8');

  assert.equal(source.includes('../src/terms.js'), false);
  assert.equal(source.includes('lookupTerm'), false);
  assert.equal(source.includes('lookupTermForPlanet'), false);
  assert.equal(source.includes('evaluateTermsForPlanets'), false);
});
