const SOURCE_KEY = 'degree-rulers-star-of-magi-table-6';
const SOURCE_SYSTEM = 'star-of-magi-degree-rulers';
const SOURCE_TABLE = 'Table 6';
const SOURCE_TITLE = 'Управление градусами по Звезде Магов';

export const DEGREE_RULERS_VERIFICATION_STATUS = Object.freeze({
  VERIFIED: 'verified',
  NEEDS_REVIEW: 'needsReview',
  DRAFT: 'draft',
  REJECTED: 'rejected',
});

export const DEGREE_RULER_SOURCE_SYSTEMS = Object.freeze({
  STAR_OF_MAGI_TABLE_6: SOURCE_SYSTEM,
  VRONSKY_TABLE_7: 'vronsky-degree-rulers-deferred',
});

export const DEGREE_RULERS_STAR_OF_MAGI_SOURCE = Object.freeze({
  sourceKey: SOURCE_KEY,
  sourceName: 'С. Вронский / Звезда Магов',
  sourceSystem: DEGREE_RULER_SOURCE_SYSTEMS.STAR_OF_MAGI_TABLE_6,
  tableNumber: 6,
  tableName: SOURCE_TITLE,
  sourceType: 'user-provided-image-and-manual-verification',
  sourceReference: 'table6.jpg',
  verificationStatus: DEGREE_RULERS_VERIFICATION_STATUS.VERIFIED,
  verificationReport: 'DEGREE_RULERS_TABLE_6_VERIFICATION_REPORT.md',
  transcriptionDraft: 'DEGREE_RULERS_TABLE_6_TRANSCRIPTION_DRAFT.md',
  rowCount: 360,
  active: true,
  enteredBy: 'Task 10.7b draft transcription',
  reviewedBy: 'Task 10.7c image-to-draft review',
  version: '1.0.0',
  notes: Object.freeze([
    'This dataset is Table 6 / Star of the Magi degree rulers only.',
    'It must not be mixed with Table 7 / Vronsky degree rulers.',
    'Only septener planets are used.',
    'No retrograde markers or multiple rulers are used in Table 6.',
  ]),
});

export const DEGREE_RULERS_DEGREE_POLICY = Object.freeze({
  type: 'integer-degree',
  validDegrees: '0 through 29',
  futureLookupRule: 'degreeIndex = floor(degreeWithinSign)',
  futureLookupValidRange: '0 <= degreeWithinSign < 30',
  degree30: 'invalid / next sign handled upstream',
  sourceSystem: DEGREE_RULER_SOURCE_SYSTEMS.STAR_OF_MAGI_TABLE_6,
});

export const DEGREE_RULERS_DEFERRED_SYSTEMS = Object.freeze({
  vronskyTable7: DEGREE_RULER_SOURCE_SYSTEMS.VRONSKY_TABLE_7,
});

export const DEGREE_RULERS_DEFERRED_FEATURES = Object.freeze([
  'VronskyTable7DegreeRulers',
  'decansTrigonVronsky',
  'fixedStars',
  'houses',
  'ASC/MC',
  'transits',
  'interpretations',
]);

const DEGREE_RULER_SIGN_LABELS = Object.freeze({
  aries: 'Овен',
  taurus: 'Телец',
  gemini: 'Близнецы',
  cancer: 'Рак',
  leo: 'Лев',
  virgo: 'Дева',
  libra: 'Весы',
  scorpio: 'Скорпион',
  sagittarius: 'Стрелец',
  capricorn: 'Козерог',
  aquarius: 'Водолей',
  pisces: 'Рыбы',
});

const DEGREE_RULER_PLANET_LABELS = Object.freeze({
  sun: 'Солнце',
  moon: 'Луна',
  mercury: 'Меркурий',
  venus: 'Венера',
  mars: 'Марс',
  jupiter: 'Юпитер',
  saturn: 'Сатурн',
});

const DEGREE_RULER_SEQUENCES_BY_SIGN = Object.freeze({
  aries: Object.freeze([
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
  ]),
  taurus: Object.freeze([
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
  ]),
  gemini: Object.freeze([
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
  ]),
  cancer: Object.freeze([
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
  ]),
  leo: Object.freeze([
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
  ]),
  virgo: Object.freeze([
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
  ]),
  libra: Object.freeze([
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
  ]),
  scorpio: Object.freeze([
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
  ]),
  sagittarius: Object.freeze([
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
  ]),
  capricorn: Object.freeze([
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
  ]),
  aquarius: Object.freeze([
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
  ]),
  pisces: Object.freeze([
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
    'mercury',
    'moon',
    'saturn',
    'jupiter',
    'mars',
    'sun',
    'venus',
  ]),
});

const DEGREE_RULER_SIGN_KEYS = Object.freeze(Object.keys(DEGREE_RULER_SIGN_LABELS));
const DEGREE_RULER_PLANET_KEYS = Object.freeze(Object.keys(DEGREE_RULER_PLANET_LABELS));
const EMPTY_ROWS = Object.freeze([]);

export const DEGREE_RULERS_STAR_OF_MAGI_ROWS = freezeRows(
  DEGREE_RULER_SIGN_KEYS.flatMap((signKey) =>
    DEGREE_RULER_SEQUENCES_BY_SIGN[signKey].map((ruler, degree) =>
      row(signKey, degree, ruler),
    ),
  ),
);

const DEGREE_RULER_ROWS_BY_SIGN = Object.freeze(
  Object.fromEntries(
    DEGREE_RULER_SIGN_KEYS.map((signKey) => [
      signKey,
      Object.freeze(DEGREE_RULERS_STAR_OF_MAGI_ROWS.filter((item) => item.sign === signKey)),
    ]),
  ),
);

const DEGREE_RULERS_STAR_OF_MAGI_DATASET = Object.freeze({
  source: DEGREE_RULERS_STAR_OF_MAGI_SOURCE,
  rows: DEGREE_RULERS_STAR_OF_MAGI_ROWS,
  signs: DEGREE_RULER_ROWS_BY_SIGN,
  rowCount: DEGREE_RULERS_STAR_OF_MAGI_ROWS.length,
  active: DEGREE_RULERS_STAR_OF_MAGI_SOURCE.active,
  degreePolicy: DEGREE_RULERS_DEGREE_POLICY,
  deferredSystems: DEGREE_RULERS_DEFERRED_SYSTEMS,
  deferredFeatures: DEGREE_RULERS_DEFERRED_FEATURES,
});

export function getDegreeRulersStarOfMagiDataset() {
  return DEGREE_RULERS_STAR_OF_MAGI_DATASET;
}

export function getDegreeRulerRowsForSign(signKey) {
  if (!isValidDegreeRulerSign(signKey)) {
    return EMPTY_ROWS;
  }

  return DEGREE_RULER_ROWS_BY_SIGN[signKey];
}

export function getDegreeRulersStarOfMagiSource() {
  return DEGREE_RULERS_STAR_OF_MAGI_SOURCE;
}

export function getDegreeRulersDeferredSystems() {
  return { ...DEGREE_RULERS_DEFERRED_SYSTEMS };
}

export function getDegreeRulersDeferredFeatures() {
  return [...DEGREE_RULERS_DEFERRED_FEATURES];
}

export function isValidDegreeRulerSign(signKey) {
  return DEGREE_RULER_SIGN_KEYS.includes(signKey);
}

export function isValidDegreeRulerPlanet(rulerKey) {
  return DEGREE_RULER_PLANET_KEYS.includes(rulerKey);
}

export function isValidDegreeIndex(degree) {
  return Number.isInteger(degree) && degree >= 0 && degree <= 29;
}

function row(sign, degree, ruler) {
  return Object.freeze({
    sourceKey: SOURCE_KEY,
    sourceSystem: DEGREE_RULER_SOURCE_SYSTEMS.STAR_OF_MAGI_TABLE_6,
    sign,
    signRu: DEGREE_RULER_SIGN_LABELS[sign],
    degree,
    ruler,
    rulerRu: DEGREE_RULER_PLANET_LABELS[ruler],
    sourceTable: SOURCE_TABLE,
    sourceTitle: SOURCE_TITLE,
    sourceRow: `${sign}-${degree}`,
    verificationStatus: DEGREE_RULERS_VERIFICATION_STATUS.VERIFIED,
    sourceCheck: 'match',
    notes: Object.freeze([]),
  });
}

function freezeRows(rows) {
  return Object.freeze([...rows]);
}
